# Generated by Django 5.0.6 on 2024-05-22 15:54

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="statment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Новая", "Новая"),
                    ("Одобрено", "Одобрено"),
                    ("Отклонено", "Отклонено"),
                ],
                default="Новая",
                max_length=254,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="statment",
            name="set_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 22, 15, 54, 7, 667490, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Выбрать время",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                max_length=30,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_phone_number",
                        message="Введите телефон +7 (ххх)-ххх-хх-хх",
                        regex="\\+7\\(\\d\\d\\d\\)-\\d\\d\\d-\\d\\d-\\d\\d",
                    )
                ],
                verbose_name="Номер телефона",
            ),
        ),
    ]
