# Generated by Django 5.0.6 on 2024-05-22 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_statment_status_alter_statment_set_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statment",
            name="set_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 22, 17, 23, 39, 627899, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Выбрать время",
            ),
        ),
    ]
